[project]
name = "flat-bug"
version = "1.1.2"
authors = [
  {name="Asger Svenning", email="asgersvenning@ecos.au.dk"},
  {name="Quentin Geissman"},
]
description = "Universal Arthropod Localization and Instance Segmentation"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch>=2.11",
    "torchvision>=0.17.0",
    "ultralytics>=8.2.16,<=8.4.49",
    "shapely>=2.0.2",
    "scikit-optimize>=0.10.1",
    "scipy>=1.14.1"
]
keywords=['deep learning', 'object detection', 'instance segmentation', 'arthropods']

[project.optional-dependencies]
erda = [
    "pyremotedata>=0.0.16"
]
cloud_datasets = [
    "boto3>=1.40",
    "cvat_sdk>=2.47"
]

[project.urls]
"Homepage" = "https://github.com/darsa-group/flat-bug"
"Bug Tracker" = "https://github.com/darsa-group/flat-bug/issues"

[project.scripts]
fb_predict = "flat_bug.cli.fb_predict:main"
fb_train = "flat_bug.cli.fb_train:main"
fb_evaluate = "flat_bug.cli.fb_eval:main"
fb_tune = "flat_bug.cli.fb_tune:main"
fb_prepare_data = "flat_bug.cli.fb_prepare_data:main"
fb_clone_data = "flat_bug.cli.fb_clone_data:main"

[dependency-groups]
docs = [
    "furo>=2025.12.19",
    "myst-parser>=5.0.0",
    "sphinx>=9.0.4",
]
notebook = [
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.0.0",
]
tests = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]

[tool.ruff]
target-version = "py311"
line-length = 140
extend-exclude = [
    "utils",
    "scripts",
    "src/flat_bug/cli/fb_tune.py",
    "examples",
    "docs"
]


[tool.ruff.lint]
# E: pycodestyle, F: Pyflakes, UP: pyupgrade, I: isort (sorts imports cleanly)
select = ["E", "F", "UP", "I", "D"]
ignore = ["D105"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pydoclint]
ignore-one-line-docstrings = true

[tool.ruff.lint.extend-per-file-ignores]
"tests/*" = ["D100"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*The NVIDIA driver on your system is too old.*:UserWarning",
    "ignore:.*`torch.jit.script.*` is deprecated.*:DeprecationWarning"
]

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"
