batch: 16
model: "./runs/segment/large/weights/best.pt"
epochs: 250
device: [0, 1]
patience: 9999
lr0: 0.01
lrf: 0.0001
optimizer: 'SGD'
workers: 60
fb_max_instances: 9999
fb_max_images: -1
fb_custom_eval: false
fb_custom_eval_num_images: 100
fb_exclude_datasets: ["ALUS", "amarathunga2022", "00-prospective-ALUS-mixed", "01-partial-gernat2018", "sticky-pi", "sittinger2023", "ubc-pitfall-traps", "anTraX", "AMT", "ArTaxOr", "01-partial-abram2023", "cao2022", "00-prospective-InsectCV", "ubc-scanned-sticky-cards", "PeMaToEuroPep", "DIRT", "01-partial-NHM-beetles-crops", "00-prospective-crall2023", "DiversityScanner", "00-prospective-chavez2024", "BIOSCAN", "pitfall", "CollembolAI", "scanned-sticky-cards"]
plots: true
name: "large_finetune"
resume: true
